### ISSUE TITLE
Report results via e-mail

### ISSUE THREAD

**Issue by mkstratos** [LIVVkit/dashboard#3]
It was requested to send a summary of the results of nightly testing to a list of interested individuals so if all tests pass, there's no need to open cdash daily.

**Comment by jhkennedy** [comment]
@mkstratos I logged into CDASH and made you a project administrator so you should be able to set up emails and what-not from CDASH for whoever (and boot me out if you want)

**Comment by mkstratos** [comment]
Thanks @jhkennedy! I didn't even realise that was a possibility...oops

**Comment by jhkennedy** [comment]
The emails aren't great, and a pretty summary would probably be nice, but you can at least get CDASH to send emails to whoever
![image](https://user-images.githubusercontent.com/7882693/95602938-1ac0fe00-0a02-11eb-9301-042ce7688374.png)
